services:
    node:
       image: node:${NODE_VERSION}
       environment:
          - VITE_BACKEND_API_URL=${VITE_BACKEND_API_URL}
       working_dir: /var/www/html
       volumes:
            - ./:/var/www/html
       restart: always
    nginx:
        image: nginx:${NGINX_VERSION}
        environment:
            - TZ=${APP_TIMEZONE}
        volumes:
            - ./logs/nginx:/var/log/nginx
            - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
        restart: always
        command: [nginx, '-g', 'daemon off;']
        ports:

            - "${NGINX_PORT}:80"
